STRIPES-856: Should have possible handle disabled state for loop by passed function.
folio-org/stripes-template-editor pull request #47
Opened 2023-04-05 11:36 UTC by Dmitriy-Litvinenko

## Purpose
Should have possible handle disabled state for loop by passed function.

## Refs
https://issues.folio.org/browse/STRIPES-856

2023-04-05 12:18 UTC, zburke requested changes
There's not enough information in the story to understand what this prop does so I can't evaluate whether it does it correctly. Please update the Jira ticket and/or the PR description.

Pedantic: I think a better name for this prop is `isDisabledLoop`.

2023-04-05 12:38 UTC, Dmitriy-Litvinenko commented
> There's not enough information in the story to understand what this prop does so I can't evaluate whether it does it correctly. Please update the Jira ticket and/or the PR description.
> 
> Pedantic: I think a better name for this prop is `isDisabledLoop`.

Hello @zburke thank you. Description updated and prop renamed. Could you please re-review?

2023-04-05 12:59 UTC, artem-blazhko approved these changes

2023-04-07 08:48 UTC, Dmitriy-Litvinenko commented
Hello @zburke Could you please re-review?

2023-04-12 14:56 UTC, Dmitriy-Litvinenko commented
Hello @zburke Could you please re-review?

2023-04-13 10:30 UTC, zburke approved these changes

2023-04-13 10:38 UTC, merged